### PR TITLE
add Typeshala

### PR DESCRIPTION
**Pull request by SushilShrestha**
- add online typeshala. An online web utility to learn Nepali typing

### CODE REVIEW

**Comment by amitness** [comment]
@SushilShrestha After merging your other two PRs, it shows merge conflicts in this PR. Could you pull the latest changes, fix the conflicts and push again to this branch?

**Comment by SushilShrestha** [comment]
Sure I will update the PR.

**Comment by SushilShrestha** [comment]
@amitness just resolved the conflict and updated the PR.

**Comment by amitness** [comment]
@SushilShrestha Thanks. The changes are merged.

**Pull request merged**
