### PR TITLE
Nepali Date Converter library

### PR DESCRIPTION
**Pull request by przbadu**
Add rubygems and .net class library for Nepali Date converter

### CODE REVIEW

**Comment by samundra** [comment]
@przbadu Please combine two commits into one single commit. Those commits are for the same purpose I guess and thus can be combined into one.

**Review by samundra — CHANGES_REQUESTED** [review]
Please combine two commits into one single commit.

**Comment by przbadu** [comment]
@samundra DONE!

**Comment by samundra** [comment]
@techgaun  @ankitpokhrel @hardfire Guys could you please have a look at it?

**Comment by ankitpokhrel** [comment]
@samundra LGTM. Can't merge as I don't have write access in this repo 😄

**Review by techgaun — APPROVED** [review]

**Pull request merged**
